#!/bin/bash
# script to open thunderbird w/ prepopulated fields
# call from folder that contains application pdf
# make variables
address=$(awk '($1 == "Email:") {print $2;}' jobdata.txt)
echo $address 
if [ -z address ]
then
	echo "Achtung: Email-Adresse fehlt in jobdata.txt"
	exit
fi

# call thunderbird
thunderbird -compose "to=$address,subject='$(head -1 current_mailsubject)',body='$(cat mail.txt)',attachment=$(echo $(pwd)/[Bb]ewerbung*)"
