#!/bin/bash
# skript zum automatischen anlegen neuer git-branches & verzeichnisse für bewerbungen in bewerb/2014
echo "Bitte gib einen kurzen Namen für den neuen branch an und drücke ENTER"
read jobname
git checkout -b stelle/$jobname
mkdir $jobname
cp ~/Dokumente/karriere/bewerb_2014/kutzner_anschreiben.tex $jobname/
# cp ~/Dokumente/karriere/bewerb_2014/ausschreibung_template.txt $jobname/ausschreibung.txt
git add .
git commit -am "new directory, added anschreiben"
