#!/bin/bash
# script to open thunderbird w/ prepopulated fields
# call from folder that contains application pdf
# make variables
#echo "Bitte gib noch einmal den Jobnamen ein: "
#read jobname
address=$(sed -n 10p jobdata.txt | cut -d: -f2 | sed "s/\s//")
echo $address 

# call thunderbird
thunderbird -compose "to=$address,subject='$(head -1 current_mailsubject)',body='$(cat mail.txt)',attachment=$(echo $(pwd)/?ewerbung*)"
