#!/bin/bash
# skript zum automatischen anlegen neuer git-branches & verzeichnisse für bewerbungen; im Bewerbungs-Oberverzeichnis zu gebrauchen
echo "Bitte gib einen kurzen Namen für den neuen branch an und drücke ENTER"
read jobname

mkdir -p $(date +%m)/$jobname

# cp -n ausschreibung_template.txt $(date +%m)/$jobname/ausschreibung.txt
cp -n templatedata/jobdata.txt  $(date +%m)/$jobname/
# cp -n cvphoto.jpg $(date +%m)/$jobname/ # in case you use a photo in your cv
# cp -n unterschrift.jpg $(date +%m)/$jobname # in case you want to use a scan of your signature

# contributed by theknittingcat
if [-f current_jobdirectory] # Todo: add OR condition to check for both
then
    echo "ERROR: File jobdirectory exists.  No changes made."
else
    echo $jobname > current_jobname
    echo $(date +%m)/$jobname > current_jobdirectory
fi
