#!/bin/bash
# This script generates mail.txt which, in turn, becomes the body text for the mail. Planned feature: strip unnecessary lines from text files, keep only opening of body of cover letter, but maybe add salutation (this could also be handled by mail-composition script).

detex anschreiben.tex > mail.txt
gedit mail.txt &


