#!/bin/bash
# generates pdf from anschreiben, concatenates it with current cv & testimonials
# generate anschreiben pdf
pdflatex anschreiben.tex

# add user prompt for naming
read -p "Bitte gib deinen Namen ein: " name
echo "OK, $name, let's go!"

# add user prompt: Where is CV?
read -p "Bitte gib 1 ein, wenn das CV in diesem Ordner liegt, 2, wenn es im übergeordneten Ordner liegt, und 3, wenn das CV im Ordner zwei Ebenen höher liegt: " cvwhere

# generate cv pdf
if [ "$cvwhere" == "1" ]  
	then
		pdflatex cv-current.tex
	elif [ "$cvwhere" == "2" ]
		then
			pdflatex ../cv-current.tex
	else
		pdflatex ../../cv-current.tex
fi	

# user prompt: include work sample?
read -p "Soll eine Arbeitsprobe angehängt werden? Bitte gibt 'y' für 'ja' oder 'n' für 'nein' ein:" sample

pdfjoin anschreiben.pdf cv-current.pdf *eugnisse.pdf --outfile Bewerbung\ $name.pdf
rm *.aux *.log *.out
